import { env } from 'cloudflare:workers';
import { DEFAULT_LANG } from '../lib/site';

// Serves /llms.txt — the LLM-oriented site index (llmstxt.org convention).
// Pre-generated by scripts/generate_llms.js and stored as a single R2 object, so
// this route is one R2 read (NOT a live crawl of every chapter, which would blow
// the Workers free-tier 50-subrequest limit). Edge-cached by the middleware.
export const prerender = false;

export async function GET() {
  if (!env.R2) {
    return new Response('R2 binding unavailable', { status: 500 });
  }
  const obj = await env.R2.get(`public-content/${DEFAULT_LANG}/llms.txt`);
  if (!obj) {
    return new Response('llms.txt not generated yet', { status: 404 });
  }
  return new Response(obj.body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
