import { env } from 'cloudflare:workers';
import { DEFAULT_LANG } from '../lib/site';

// Serves /llms-full.txt — the entire English corpus as one Markdown document.
// Pre-generated by scripts/generate_llms.js (in Node, reading local content-
// source, so no per-request fan-out) and stored as a single R2 object. Serving
// it is one R2 read; the edge-cache middleware holds it after the first hit.
export const prerender = false;

export async function GET() {
  if (!env.R2) {
    return new Response('R2 binding unavailable', { status: 500 });
  }
  const obj = await env.R2.get(`public-content/${DEFAULT_LANG}/llms-full.txt`);
  if (!obj) {
    return new Response('llms-full.txt not generated yet', { status: 404 });
  }
  return new Response(obj.body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
