/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Cloudflare runtime types, the bindings `Env` (R2, MANIFEST, ASSETS), and the
// `cloudflare:workers` module are provided by worker-configuration.d.ts, which
// is generated by `wrangler types` from wrangler.toml. Rerun `npx wrangler
// types` after changing bindings. Bindings are accessed via
// `import { env } from 'cloudflare:workers'`.

type Runtime = import('@astrojs/cloudflare').Runtime;

declare namespace App {
  interface Locals extends Runtime {}
}
